### PR TITLE
Parse using "parse-sass-value" instead of JSON.stringify

### PR DESCRIPTION
**Pull request by VitorLuizC**
I've created `parse-sass-value` module to parse JavaScript values, including objects & arrays, to SASS values. It also handle colors and CSS lengths as primitive values instead of string.

Now, this
```js
variables({
  'title-size': '12px',
  'title-family': [ 'Roboto', 'sans-serif' ],
  'title-line': 1.5,
  'button-theme': {
    size: '300px',
    dark: true
  }
})
```
will be parsed into
```scss
$title-size: 12px;
$title-family: ( 'Roboto', 'sans-serif');
$title-line: 1.5;
$button-theme: (
  'size': 300px,
  'dark': true
);
```

### CODE REVIEW

**Comment by cbratschi** [comment]
When will this be integrated? Currently colors, such as green are passed as quoted strings which is not CSS compliant.

**Comment by VitorLuizC** [comment]
@cbratschi you can use [`gulp-sass-vars`](https://github.com/giowe/gulp-sass-vars) instead or use `gulp-header` with `parse-sass-value`.

```js
'use strict';

const gulp = require('gulp');
const sass = require('gulp-sass');
const parse = require('parse-sass-value');
const header = require('gulp-header');

function variables (variables = {}) {
  const toStatement = ([name, value]) => `$${name}: ${parse(value)};`;
  return header(Object.entries(variables).map(toStatement).join('\n'));
};

gulp.task('build', () => {
  gulp.src('./styles/style.scss')
    .pipe(variables({
      'theme-color': 'green'
    }))
    .pipe(sass())
    .pipe(gulp.dest('./dist/style.css'))
});
```

**Comment by cbratschi** [comment]
@VitorLuizC thanks for pointing me to gulp-sass-vars. This works perfectly fine and without $ prefixes it is even more user friendly.

**Comment by osaton** [comment]
Thanks for the pull request and sorry for taking so long to answer.

This would be a breaking change and would demand a new major version, since I can't be certain if someone is actually counting on those quoted colors in their SASS (e.g. `$theme == 'green'`).

It would also make this almost identical with `gulp-sass-vars` so I think I'll keep this one a bare boned version at least for now.

**Comment by VitorLuizC** [comment]
@osaton I can add a setting to prevent this on `parse-sass-value`. Would it fix this scenario?

```js
import parse from 'parse-sass-value';

const theme = parse('green', {
  quotes: 'double',
  escapeColors: false
});
//=> "green"
```

**Pull request closed without merging**
